### ISSUE TITLE
Compile bug

### ISSUE THREAD

**Issue by janhartmann** [azzlack/Sentinel.OAuth#4]
Hi Azzlack

Stumbled across this library and wanted to try it out, using the SqlServerTokenRepository, but some how this error appears on start up:

> The method 'GetAuthorizationCode' of type 'Sentinel.OAuth.TokenManagers.SqlServerTokenRepository.Implementation.SqlServerTokenRepository' fra assemblyen 'Sentinel.OAuth.TokenManagers.SqlServerTokenRepository, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'  has not been implemented.

Is the NuGet packages updated, also are you still actively maintaining this library?

Thanks.

**Comment by azzlack** [comment]
Sorry for the late answer. Yes I am actively using this library and maintaining it. Are you sure you are using the latest versions?
